// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethodTest - Use 'RecordedMethodTestParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethodTest()
        {
            #region Variable Declarations
            WinClient uIChromeLegacyWindowClient = this.UISpotifyWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowClient;
            WinControl uIItemDocument = this.UISpotifyWindow.UIChromeLegacyWindowWindow.UIItemDocument;
            WinControl uIChromeLegacyWindowDocument = this.UISpotifyWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(74, 83));

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(141, 27));

            // Type 't' in document
            Keyboard.SendKeys(uIItemDocument, this.RecordedMethodTestParams.UIItemDocumentSendKeys, ModifierKeys.None);

            // Type 'he lonely island{Enter}' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.RecordedMethodTestParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(252, 618));
        }
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfWindow uIWpfWindow = this.UIWpfWindow;
            WpfEdit uIMitNameEdit = this.UIMainWindowWindow.UINewEmployeexamlPane.UIMitNameEdit;
            WpfEdit uIMitVornameEdit = this.UIMainWindowWindow.UINewEmployeexamlPane.UIMitVornameEdit;
            #endregion

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(59, 72));

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(152, 61));

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(150, 19));

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(365, 78));

            // Type 'John' in 'mitName' text box
            uIMitNameEdit.Text = this.RecordedMethod1Params.UIMitNameEditText;

            // Type '{Tab}' in 'mitName' text box
            Keyboard.SendKeys(uIMitNameEdit, this.RecordedMethod1Params.UIMitNameEditSendKeys, ModifierKeys.None);

            // Type 'Francis' in 'mitVorname' text box
            uIMitVornameEdit.Text = this.RecordedMethod1Params.UIMitVornameEditText;

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(352, 131));

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(722, 161));

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(123, 97));

            // Click 'Wpf' window
            Mouse.Click(uIWpfWindow, new Point(130, 35));
        }
        
        /// <summary>
        /// CreateMitarbeiter - Use 'CreateMitarbeiterParams' to pass parameters into this method.
        /// </summary>
        public void CreateMitarbeiter()
        {
            #region Variable Declarations
            WpfWindow uIMainWindowWindow = this.UIMainWindowWindow;
            WpfButton uIMitarbeiterHinzufügeButton = this.UIMainWindowWindow.UIMitarbeiterHinzufügeButton;
            WpfEdit uIMitNameEdit = this.UIMainWindowWindow.UINewEmployeexamlPane.UIMitNameEdit;
            WpfEdit uIMitVornameEdit = this.UIMainWindowWindow.UINewEmployeexamlPane.UIMitVornameEdit;
            WpfCheckBox uIMitAktivCheckBox = this.UIMainWindowWindow.UINewEmployeexamlPane.UIMitAktivCheckBox;
            WpfButton uISpeichernButton = this.UIMainWindowWindow.UINewEmployeexamlPane.UISpeichernButton;
            WpfButton uIMitarbeiterListenansButton = this.UIMainWindowWindow.UIMitarbeiterListenansButton;
            WpfList uIMitListBoxList = this.UIMainWindowWindow.UINewEmployeexamlPane.UIMitListBoxList;
            #endregion

            // Click 'MainWindow' window
            Mouse.Click(uIMainWindowWindow, new Point(126, 271));

            // Click 'Mitarbeiter Hinzufügen' button
            Mouse.Click(uIMitarbeiterHinzufügeButton, new Point(120, 13));

            // Type 'John' in 'mitName' text box
            uIMitNameEdit.Text = this.CreateMitarbeiterParams.UIMitNameEditText;

            // Type '{Tab}' in 'mitName' text box
            Keyboard.SendKeys(uIMitNameEdit, this.CreateMitarbeiterParams.UIMitNameEditSendKeys, ModifierKeys.None);

            // Type 'Francis' in 'mitVorname' text box
            uIMitVornameEdit.Text = this.CreateMitarbeiterParams.UIMitVornameEditText;

            // Select 'mitAktiv' check box
            uIMitAktivCheckBox.Checked = this.CreateMitarbeiterParams.UIMitAktivCheckBoxChecked;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton, new Point(8, 8));

            // Click 'Mitarbeiter Listenansicht' button
            Mouse.Click(uIMitarbeiterListenansButton, new Point(132, 8));

            // Select 'John' in 'mitListBox' list box
            uIMitListBoxList.SelectedItemsAsString = this.CreateMitarbeiterParams.UIMitListBoxListSelectedItemsAsString;
        }
        
        /// <summary>
        /// CheckUser - Use 'CheckUserExpectedValues' to pass parameters into this method.
        /// </summary>
        public void CheckUser()
        {
            #region Variable Declarations
            WpfListItem uIJohnListItem = this.UIMainWindowWindow.UINewEmployeexamlPane.UIMitListBoxList.UIJohnListItem;
            #endregion

            // Verify that the 'Name' property of 'John' list item equals 'John'
            Assert.AreEqual(this.CheckUserExpectedValues.UIJohnListItemName, uIJohnListItem.Name, "Name doesn\'t match");
        }
        
        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WpfWindow uIMainWindowWindow = this.UIMainWindowWindow;
            WpfButton uINeueEinsatzButton = this.UIMainWindowWindow.UINeueEinsatzButton;
            WpfEdit uIJobNameEdit = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobNameEdit;
            WpfComboBox uIJobProjComboBox = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobProjComboBox;
            WpfDatePicker uIJobStartDatePicker = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobStartDatePicker;
            WpfDatePicker uIJobEndDatePicker = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobEndDatePicker;
            WpfButton uISpeichernButton1 = this.UIMainWindowWindow.UINewEmployeexamlPane.UISpeichernButton1;
            #endregion

            // Click 'MainWindow' window
            Mouse.Click(uIMainWindowWindow, new Point(136, 282));

            // Click 'Neue Einsatz' button
            Mouse.Click(uINeueEinsatzButton, new Point(140, 7));

            // Type 'Test' in 'jobName' text box
            uIJobNameEdit.Text = this.RecordedMethod2Params.UIJobNameEditText;

            // Select 'Projekt YellowLabel' in 'jobProj' combo box
            uIJobProjComboBox.SelectedItem = this.RecordedMethod2Params.UIJobProjComboBoxSelectedItem;

            // Select '06-Jun-2016' in 'jobStart' date picker
            uIJobStartDatePicker.DateAsString = this.RecordedMethod2Params.UIJobStartDatePickerDateAsString;

            // Select '06-Jun-2016' in 'jobEnd' date picker
            uIJobEndDatePicker.DateAsString = this.RecordedMethod2Params.UIJobEndDatePickerDateAsString;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton1, new Point(29, 12));
        }
        
        /// <summary>
        /// CreateJob - Use 'CreateJobParams' to pass parameters into this method.
        /// </summary>
        public void CreateJob()
        {
            #region Variable Declarations
            WpfWindow uIMainWindowWindow = this.UIMainWindowWindow;
            WpfButton uINeueEinsatzButton = this.UIMainWindowWindow.UINeueEinsatzButton;
            WpfEdit uIJobNameEdit = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobNameEdit;
            WpfComboBox uIJobMitComboBox = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobMitComboBox;
            WpfComboBox uIJobProjComboBox = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobProjComboBox;
            WpfDatePicker uIJobStartDatePicker = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobStartDatePicker;
            WpfDatePicker uIJobEndDatePicker = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobEndDatePicker;
            WpfButton uISpeichernButton1 = this.UIMainWindowWindow.UINewEmployeexamlPane.UISpeichernButton1;
            WpfButton uIEinsatzListenansichtButton = this.UIMainWindowWindow.UIEinsatzListenansichtButton;
            #endregion

            // Click 'MainWindow' window
            Mouse.Click(uIMainWindowWindow, new Point(80, 309));

            // Click 'Neue Einsatz' button
            Mouse.Click(uINeueEinsatzButton, new Point(119, 8));

            // Type 'Test' in 'jobName' text box
            uIJobNameEdit.Text = this.CreateJobParams.UIJobNameEditText;

            // Select 'Affolter' in 'jobMit' combo box
            uIJobMitComboBox.SelectedItem = this.CreateJobParams.UIJobMitComboBoxSelectedItem;

            // Select 'Projekt YellowLabel' in 'jobProj' combo box
            uIJobProjComboBox.SelectedItem = this.CreateJobParams.UIJobProjComboBoxSelectedItem;

            // Select '06-Jun-2016' in 'jobStart' date picker
            uIJobStartDatePicker.DateAsString = this.CreateJobParams.UIJobStartDatePickerDateAsString;

            // Select '06-Jun-2016' in 'jobEnd' date picker
            uIJobEndDatePicker.DateAsString = this.CreateJobParams.UIJobEndDatePickerDateAsString;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton1, new Point(31, 12));

            // Click 'Einsatz Listenansicht' button
            Mouse.Click(uIEinsatzListenansichtButton, new Point(126, 8));
        }
        
        /// <summary>
        /// AssertJobCreated - Use 'AssertJobCreatedExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertJobCreated()
        {
            #region Variable Declarations
            WpfListItem uITestListItem = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobsListBoxList.UITestListItem;
            #endregion

            // Verify that the 'Name' property of 'Test' list item equals 'Test'
            Assert.AreEqual(this.AssertJobCreatedExpectedValues.UITestListItemName, uITestListItem.Name, "Failed to Create Job \"Test\"");
        }
        
        /// <summary>
        /// CleanUp
        /// </summary>
        public void CleanUp()
        {
            #region Variable Declarations
            WpfWindow uIMainWindowWindow = this.UIMainWindowWindow;
            WinButton uICloseButton = this.UIMainWindowWindow1.UICloseButton;
            #endregion

            // Click 'MainWindow' window
            Mouse.Click(uIMainWindowWindow, new Point(441, 312));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(28, 17));
        }
        
        /// <summary>
        /// EditJob - Use 'EditJobParams' to pass parameters into this method.
        /// </summary>
        public void EditJob()
        {
            #region Variable Declarations
            WpfWindow uIMainWindowWindow = this.UIMainWindowWindow;
            WpfListItem uITest1ListItem = this.UIMainWindowWindow.UINewEmployeexamlPane.UIItemList.UITest1ListItem;
            WpfDatePicker uIJobStartDatePicker = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobStartDatePicker;
            WpfDatePicker uIJobEndDatePicker = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobEndDatePicker;
            WpfButton uISpeichernButton1 = this.UIMainWindowWindow.UINewEmployeexamlPane.UISpeichernButton1;
            WpfButton uIEinsatzListenansichtButton = this.UIMainWindowWindow.UIEinsatzListenansichtButton;
            #endregion

            // Click 'MainWindow' window
            Mouse.Click(uIMainWindowWindow, new Point(115, 300));

            // Double-Click 'Test1' list item
            Mouse.DoubleClick(uITest1ListItem, new Point(35, 5));

            // Select '08-Jun-2016' in 'jobStart' date picker
            uIJobStartDatePicker.DateAsString = this.EditJobParams.UIJobStartDatePickerDateAsString;

            // Select '08-Jun-2016' in 'jobEnd' date picker
            uIJobEndDatePicker.DateAsString = this.EditJobParams.UIJobEndDatePickerDateAsString;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton1, new Point(39, 6));

            // Click 'Einsatz Listenansicht' button
            Mouse.Click(uIEinsatzListenansichtButton, new Point(149, 9));
        }
        
        /// <summary>
        /// JobEdit - Use 'JobEditParams' to pass parameters into this method.
        /// </summary>
        public void JobEdit()
        {
            #region Variable Declarations
            WpfWindow uIMainWindowWindow = this.UIMainWindowWindow;
            WpfListItem uITest1ListItem = this.UIMainWindowWindow.UINewEmployeexamlPane.UIItemList.UITest1ListItem;
            WpfDatePicker uIJobStartDatePicker = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobStartDatePicker;
            WpfDatePicker uIJobEndDatePicker = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobEndDatePicker;
            WpfButton uISpeichernButton1 = this.UIMainWindowWindow.UINewEmployeexamlPane.UISpeichernButton1;
            WpfButton uIEinsatzListenansichtButton = this.UIMainWindowWindow.UIEinsatzListenansichtButton;
            #endregion

            // Click 'MainWindow' window
            Mouse.Click(uIMainWindowWindow, new Point(108, 288));

            // Double-Click 'Test1' list item
            Mouse.DoubleClick(uITest1ListItem, new Point(40, 11));

            // Select '08-Jun-2016' in 'jobStart' date picker
            uIJobStartDatePicker.DateAsString = this.JobEditParams.UIJobStartDatePickerDateAsString;

            // Select '08-Jun-2016' in 'jobEnd' date picker
            uIJobEndDatePicker.DateAsString = this.JobEditParams.UIJobEndDatePickerDateAsString;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton1, new Point(40, 8));

            // Click 'Einsatz Listenansicht' button
            Mouse.Click(uIEinsatzListenansichtButton, new Point(123, 5));
        }
        
        /// <summary>
        /// CheckEditJob - Use 'CheckEditJobExpectedValues' to pass parameters into this method.
        /// </summary>
        public void CheckEditJob()
        {
            #region Variable Declarations
            WpfListItem uITest1682016120000AMListItem = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobsListBoxList.UITest1682016120000AMListItem;
            #endregion

            // Verify that the 'Name' property of 'Test1 - 6/8/2016 12:00:00 AM' list item equals 'Test1 - 6/8/2016 12:00:00 AM'
            Assert.AreEqual(this.CheckEditJobExpectedValues.UITest1682016120000AMListItemName, uITest1682016120000AMListItem.Name, "Check If Change Success");
        }
        
        /// <summary>
        /// CleanUpEdit
        /// </summary>
        public void CleanUpEdit()
        {
            #region Variable Declarations
            WpfWindow uIMainWindowWindow = this.UIMainWindowWindow;
            WinButton uICloseButton = this.UIMainWindowWindow1.UICloseButton;
            #endregion

            // Click 'MainWindow' window
            Mouse.Click(uIMainWindowWindow, new Point(538, 356));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(19, 11));
        }
        
        /// <summary>
        /// CreateJobDouble - Use 'CreateJobDoubleParams' to pass parameters into this method.
        /// </summary>
        public void CreateJobDouble()
        {
            #region Variable Declarations
            WpfWindow uIMainWindowWindow = this.UIMainWindowWindow;
            WpfButton uINeueEinsatzButton = this.UIMainWindowWindow.UINeueEinsatzButton;
            WpfEdit uIJobNameEdit = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobNameEdit;
            WpfDatePicker uIJobStartDatePicker = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobStartDatePicker;
            WpfDatePicker uIJobEndDatePicker = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobEndDatePicker;
            WpfButton uISpeichernButton1 = this.UIMainWindowWindow.UINewEmployeexamlPane.UISpeichernButton1;
            #endregion

            // Click 'MainWindow' window
            Mouse.Click(uIMainWindowWindow, new Point(111, 301));

            // Click 'Neue Einsatz' button
            Mouse.Click(uINeueEinsatzButton, new Point(109, 11));

            // Type 'DoubleJob' in 'jobName' text box
            uIJobNameEdit.Text = this.CreateJobDoubleParams.UIJobNameEditText;

            // Select '10-Jun-2016' in 'jobStart' date picker
            uIJobStartDatePicker.DateAsString = this.CreateJobDoubleParams.UIJobStartDatePickerDateAsString;

            // Select '10-Jun-2016' in 'jobEnd' date picker
            uIJobEndDatePicker.DateAsString = this.CreateJobDoubleParams.UIJobEndDatePickerDateAsString;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton1, new Point(25, 12));
        }
        
        /// <summary>
        /// CheckEditJobDouble - Use 'CheckEditJobDoubleExpectedValues' to pass parameters into this method.
        /// </summary>
        public void CheckEditJobDouble()
        {
            #region Variable Declarations
            WpfText uIDoppeleinsatzfürMitaText = this.UIMainWindowWindow.UINewEmployeexamlPane.UIDoppeleinsatzfürMitaText;
            #endregion

            // Verify that the 'DisplayText' property of 'Doppeleinsatz für Mitarbeiter. Das ist Nicht Erlau...' label equals 'Doppeleinsatz für Mitarbeiter. Das ist Nicht Erlaubt!'
            Assert.AreEqual(this.CheckEditJobDoubleExpectedValues.UIDoppeleinsatzfürMitaTextDisplayText, uIDoppeleinsatzfürMitaText.DisplayText, "Error Message Didn\'t Show.. it should\'ve");
        }
        
        /// <summary>
        /// CleanUpJobDouble
        /// </summary>
        public void CleanUpJobDouble()
        {
            #region Variable Declarations
            WpfWindow uIMainWindowWindow = this.UIMainWindowWindow;
            WinButton uICloseButton = this.UIMainWindowWindow1.UICloseButton;
            #endregion

            // Click 'MainWindow' window
            Mouse.Click(uIMainWindowWindow, new Point(607, 395));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(18, 9));
        }
        
        /// <summary>
        /// CheckCreateJob - Use 'CheckCreateJobExpectedValues' to pass parameters into this method.
        /// </summary>
        public void CheckCreateJob()
        {
            #region Variable Declarations
            WpfListItem uITest662016120000AMListItem = this.UIMainWindowWindow.UINewEmployeexamlPane.UIJobsListBoxList.UITest662016120000AMListItem;
            #endregion

            // Verify that the 'DisplayText' property of 'Test - 6/6/2016 12:00:00 AM' list item equals 'Test - 6/6/2016 12:00:00 AM'
            Assert.AreEqual(this.CheckCreateJobExpectedValues.UITest662016120000AMListItemDisplayText, uITest662016120000AMListItem.DisplayText, "Failed to create job");
        }
        
        /// <summary>
        /// CleanUpCreatejob
        /// </summary>
        public void CleanUpCreatejob()
        {
            #region Variable Declarations
            WpfWindow uIMainWindowWindow = this.UIMainWindowWindow;
            WinButton uICloseButton = this.UIMainWindowWindow1.UICloseButton;
            #endregion

            // Click 'MainWindow' window
            Mouse.Click(uIMainWindowWindow, new Point(569, 372));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(18, 15));
        }
        
        #region Properties
        public virtual RecordedMethodTestParams RecordedMethodTestParams
        {
            get
            {
                if ((this.mRecordedMethodTestParams == null))
                {
                    this.mRecordedMethodTestParams = new RecordedMethodTestParams();
                }
                return this.mRecordedMethodTestParams;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual CreateMitarbeiterParams CreateMitarbeiterParams
        {
            get
            {
                if ((this.mCreateMitarbeiterParams == null))
                {
                    this.mCreateMitarbeiterParams = new CreateMitarbeiterParams();
                }
                return this.mCreateMitarbeiterParams;
            }
        }
        
        public virtual CheckUserExpectedValues CheckUserExpectedValues
        {
            get
            {
                if ((this.mCheckUserExpectedValues == null))
                {
                    this.mCheckUserExpectedValues = new CheckUserExpectedValues();
                }
                return this.mCheckUserExpectedValues;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public virtual CreateJobParams CreateJobParams
        {
            get
            {
                if ((this.mCreateJobParams == null))
                {
                    this.mCreateJobParams = new CreateJobParams();
                }
                return this.mCreateJobParams;
            }
        }
        
        public virtual AssertJobCreatedExpectedValues AssertJobCreatedExpectedValues
        {
            get
            {
                if ((this.mAssertJobCreatedExpectedValues == null))
                {
                    this.mAssertJobCreatedExpectedValues = new AssertJobCreatedExpectedValues();
                }
                return this.mAssertJobCreatedExpectedValues;
            }
        }
        
        public virtual EditJobParams EditJobParams
        {
            get
            {
                if ((this.mEditJobParams == null))
                {
                    this.mEditJobParams = new EditJobParams();
                }
                return this.mEditJobParams;
            }
        }
        
        public virtual JobEditParams JobEditParams
        {
            get
            {
                if ((this.mJobEditParams == null))
                {
                    this.mJobEditParams = new JobEditParams();
                }
                return this.mJobEditParams;
            }
        }
        
        public virtual CheckEditJobExpectedValues CheckEditJobExpectedValues
        {
            get
            {
                if ((this.mCheckEditJobExpectedValues == null))
                {
                    this.mCheckEditJobExpectedValues = new CheckEditJobExpectedValues();
                }
                return this.mCheckEditJobExpectedValues;
            }
        }
        
        public virtual CreateJobDoubleParams CreateJobDoubleParams
        {
            get
            {
                if ((this.mCreateJobDoubleParams == null))
                {
                    this.mCreateJobDoubleParams = new CreateJobDoubleParams();
                }
                return this.mCreateJobDoubleParams;
            }
        }
        
        public virtual CheckEditJobDoubleExpectedValues CheckEditJobDoubleExpectedValues
        {
            get
            {
                if ((this.mCheckEditJobDoubleExpectedValues == null))
                {
                    this.mCheckEditJobDoubleExpectedValues = new CheckEditJobDoubleExpectedValues();
                }
                return this.mCheckEditJobDoubleExpectedValues;
            }
        }
        
        public virtual CheckCreateJobExpectedValues CheckCreateJobExpectedValues
        {
            get
            {
                if ((this.mCheckCreateJobExpectedValues == null))
                {
                    this.mCheckCreateJobExpectedValues = new CheckCreateJobExpectedValues();
                }
                return this.mCheckCreateJobExpectedValues;
            }
        }
        
        public UISpotifyWindow UISpotifyWindow
        {
            get
            {
                if ((this.mUISpotifyWindow == null))
                {
                    this.mUISpotifyWindow = new UISpotifyWindow();
                }
                return this.mUISpotifyWindow;
            }
        }
        
        public UIWpfWindow UIWpfWindow
        {
            get
            {
                if ((this.mUIWpfWindow == null))
                {
                    this.mUIWpfWindow = new UIWpfWindow();
                }
                return this.mUIWpfWindow;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        
        public UIMainWindowWindow1 UIMainWindowWindow1
        {
            get
            {
                if ((this.mUIMainWindowWindow1 == null))
                {
                    this.mUIMainWindowWindow1 = new UIMainWindowWindow1();
                }
                return this.mUIMainWindowWindow1;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethodTestParams mRecordedMethodTestParams;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private CreateMitarbeiterParams mCreateMitarbeiterParams;
        
        private CheckUserExpectedValues mCheckUserExpectedValues;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private CreateJobParams mCreateJobParams;
        
        private AssertJobCreatedExpectedValues mAssertJobCreatedExpectedValues;
        
        private EditJobParams mEditJobParams;
        
        private JobEditParams mJobEditParams;
        
        private CheckEditJobExpectedValues mCheckEditJobExpectedValues;
        
        private CreateJobDoubleParams mCreateJobDoubleParams;
        
        private CheckEditJobDoubleExpectedValues mCheckEditJobDoubleExpectedValues;
        
        private CheckCreateJobExpectedValues mCheckCreateJobExpectedValues;
        
        private UISpotifyWindow mUISpotifyWindow;
        
        private UIWpfWindow mUIWpfWindow;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        
        private UIMainWindowWindow1 mUIMainWindowWindow1;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethodTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethodTestParams
    {
        
        #region Fields
        /// <summary>
        /// Type 't' in document
        /// </summary>
        public string UIItemDocumentSendKeys = "t";
        
        /// <summary>
        /// Type 'he lonely island{Enter}' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "he lonely island{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'John' in 'mitName' text box
        /// </summary>
        public string UIMitNameEditText = "John";
        
        /// <summary>
        /// Type '{Tab}' in 'mitName' text box
        /// </summary>
        public string UIMitNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Francis' in 'mitVorname' text box
        /// </summary>
        public string UIMitVornameEditText = "Francis";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CreateMitarbeiter'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CreateMitarbeiterParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'John' in 'mitName' text box
        /// </summary>
        public string UIMitNameEditText = "John";
        
        /// <summary>
        /// Type '{Tab}' in 'mitName' text box
        /// </summary>
        public string UIMitNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Francis' in 'mitVorname' text box
        /// </summary>
        public string UIMitVornameEditText = "Francis";
        
        /// <summary>
        /// Select 'mitAktiv' check box
        /// </summary>
        public bool UIMitAktivCheckBoxChecked = true;
        
        /// <summary>
        /// Select 'John' in 'mitListBox' list box
        /// </summary>
        public string UIMitListBoxListSelectedItemsAsString = "John";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CheckUser'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CheckUserExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'John' list item equals 'John'
        /// </summary>
        public string UIJohnListItemName = "John";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'Test' in 'jobName' text box
        /// </summary>
        public string UIJobNameEditText = "Test";
        
        /// <summary>
        /// Select 'Projekt YellowLabel' in 'jobProj' combo box
        /// </summary>
        public string UIJobProjComboBoxSelectedItem = "Projekt YellowLabel";
        
        /// <summary>
        /// Select '06-Jun-2016' in 'jobStart' date picker
        /// </summary>
        public string UIJobStartDatePickerDateAsString = "06-Jun-2016";
        
        /// <summary>
        /// Select '06-Jun-2016' in 'jobEnd' date picker
        /// </summary>
        public string UIJobEndDatePickerDateAsString = "06-Jun-2016";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CreateJob'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CreateJobParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Test' in 'jobName' text box
        /// </summary>
        public string UIJobNameEditText = "Test";
        
        /// <summary>
        /// Select 'Affolter' in 'jobMit' combo box
        /// </summary>
        public string UIJobMitComboBoxSelectedItem = "Affolter";
        
        /// <summary>
        /// Select 'Projekt YellowLabel' in 'jobProj' combo box
        /// </summary>
        public string UIJobProjComboBoxSelectedItem = "Projekt YellowLabel";
        
        /// <summary>
        /// Select '06-Jun-2016' in 'jobStart' date picker
        /// </summary>
        public string UIJobStartDatePickerDateAsString = "06-Jun-2016";
        
        /// <summary>
        /// Select '06-Jun-2016' in 'jobEnd' date picker
        /// </summary>
        public string UIJobEndDatePickerDateAsString = "06-Jun-2016";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertJobCreated'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertJobCreatedExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Test' list item equals 'Test'
        /// </summary>
        public string UITestListItemName = "Test";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EditJob'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class EditJobParams
    {
        
        #region Fields
        /// <summary>
        /// Select '08-Jun-2016' in 'jobStart' date picker
        /// </summary>
        public string UIJobStartDatePickerDateAsString = "08-Jun-2016";
        
        /// <summary>
        /// Select '08-Jun-2016' in 'jobEnd' date picker
        /// </summary>
        public string UIJobEndDatePickerDateAsString = "08-Jun-2016";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'JobEdit'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class JobEditParams
    {
        
        #region Fields
        /// <summary>
        /// Select '08-Jun-2016' in 'jobStart' date picker
        /// </summary>
        public string UIJobStartDatePickerDateAsString = "08-Jun-2016";
        
        /// <summary>
        /// Select '08-Jun-2016' in 'jobEnd' date picker
        /// </summary>
        public string UIJobEndDatePickerDateAsString = "08-Jun-2016";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CheckEditJob'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CheckEditJobExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Test1 - 6/8/2016 12:00:00 AM' list item equals 'Test1 - 6/8/2016 12:00:00 AM'
        /// </summary>
        public string UITest1682016120000AMListItemName = "Test1 - 6/8/2016 12:00:00 AM";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CreateJobDouble'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CreateJobDoubleParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'DoubleJob' in 'jobName' text box
        /// </summary>
        public string UIJobNameEditText = "DoubleJob";
        
        /// <summary>
        /// Select '10-Jun-2016' in 'jobStart' date picker
        /// </summary>
        public string UIJobStartDatePickerDateAsString = "10-Jun-2016";
        
        /// <summary>
        /// Select '10-Jun-2016' in 'jobEnd' date picker
        /// </summary>
        public string UIJobEndDatePickerDateAsString = "10-Jun-2016";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CheckEditJobDouble'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CheckEditJobDoubleExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'DisplayText' property of 'Doppeleinsatz für Mitarbeiter. Das ist Nicht Erlau...' label equals 'Doppeleinsatz für Mitarbeiter. Das ist Nicht Erlaubt!'
        /// </summary>
        public string UIDoppeleinsatzfürMitaTextDisplayText = "Doppeleinsatz für Mitarbeiter. Das ist Nicht Erlaubt!";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CheckCreateJob'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CheckCreateJobExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'DisplayText' property of 'Test - 6/6/2016 12:00:00 AM' list item equals 'Test - 6/6/2016 12:00:00 AM'
        /// </summary>
        public string UITest662016120000AMListItemDisplayText = "Test - 6/6/2016 12:00:00 AM";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISpotifyWindow : WinWindow
    {
        
        public UISpotifyWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Spotify";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "SpotifyMainWindow";
            this.WindowTitles.Add("Spotify");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "180990392";
            this.WindowTitles.Add("Spotify");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Spotify");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        
        public WinControl UIItemDocument
        {
            get
            {
                if ((this.mUIItemDocument == null))
                {
                    this.mUIItemDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIItemDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIItemDocument.WindowTitles.Add("Spotify");
                    #endregion
                }
                return this.mUIItemDocument;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Spotify");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        
        private WinControl mUIItemDocument;
        
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIWpfWindow : WpfWindow
    {
        
        public UIWpfWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            #endregion
        }
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UINewEmployeexamlPane UINewEmployeexamlPane
        {
            get
            {
                if ((this.mUINewEmployeexamlPane == null))
                {
                    this.mUINewEmployeexamlPane = new UINewEmployeexamlPane(this);
                }
                return this.mUINewEmployeexamlPane;
            }
        }
        
        public WpfButton UIMitarbeiterHinzufügeButton
        {
            get
            {
                if ((this.mUIMitarbeiterHinzufügeButton == null))
                {
                    this.mUIMitarbeiterHinzufügeButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIMitarbeiterHinzufügeButton.SearchProperties[WpfButton.PropertyNames.Name] = "Mitarbeiter Hinzufügen";
                    this.mUIMitarbeiterHinzufügeButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIMitarbeiterHinzufügeButton;
            }
        }
        
        public WpfButton UIMitarbeiterListenansButton
        {
            get
            {
                if ((this.mUIMitarbeiterListenansButton == null))
                {
                    this.mUIMitarbeiterListenansButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIMitarbeiterListenansButton.SearchProperties[WpfButton.PropertyNames.Name] = "Mitarbeiter Listenansicht";
                    this.mUIMitarbeiterListenansButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIMitarbeiterListenansButton;
            }
        }
        
        public WpfButton UINeueEinsatzButton
        {
            get
            {
                if ((this.mUINeueEinsatzButton == null))
                {
                    this.mUINeueEinsatzButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUINeueEinsatzButton.SearchProperties[WpfButton.PropertyNames.Name] = "Neue Einsatz";
                    this.mUINeueEinsatzButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUINeueEinsatzButton;
            }
        }
        
        public WpfButton UIEinsatzListenansichtButton
        {
            get
            {
                if ((this.mUIEinsatzListenansichtButton == null))
                {
                    this.mUIEinsatzListenansichtButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIEinsatzListenansichtButton.SearchProperties[WpfButton.PropertyNames.Name] = "Einsatz Listenansicht";
                    this.mUIEinsatzListenansichtButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIEinsatzListenansichtButton;
            }
        }
        #endregion
        
        #region Fields
        private UINewEmployeexamlPane mUINewEmployeexamlPane;
        
        private WpfButton mUIMitarbeiterHinzufügeButton;
        
        private WpfButton mUIMitarbeiterListenansButton;
        
        private WpfButton mUINeueEinsatzButton;
        
        private WpfButton mUIEinsatzListenansichtButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINewEmployeexamlPane : WpfPane
    {
        
        public UINewEmployeexamlPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.Frame";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "pagesFrame";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIMitNameEdit
        {
            get
            {
                if ((this.mUIMitNameEdit == null))
                {
                    this.mUIMitNameEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIMitNameEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "mitName";
                    this.mUIMitNameEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIMitNameEdit;
            }
        }
        
        public WpfEdit UIMitVornameEdit
        {
            get
            {
                if ((this.mUIMitVornameEdit == null))
                {
                    this.mUIMitVornameEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIMitVornameEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "mitVorname";
                    this.mUIMitVornameEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIMitVornameEdit;
            }
        }
        
        public WpfCheckBox UIMitAktivCheckBox
        {
            get
            {
                if ((this.mUIMitAktivCheckBox == null))
                {
                    this.mUIMitAktivCheckBox = new WpfCheckBox(this);
                    #region Search Criteria
                    this.mUIMitAktivCheckBox.SearchProperties[WpfCheckBox.PropertyNames.AutomationId] = "mitAktiv";
                    this.mUIMitAktivCheckBox.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIMitAktivCheckBox;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "mitSubmit";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        
        public UIMitListBoxList UIMitListBoxList
        {
            get
            {
                if ((this.mUIMitListBoxList == null))
                {
                    this.mUIMitListBoxList = new UIMitListBoxList(this);
                }
                return this.mUIMitListBoxList;
            }
        }
        
        public WpfEdit UIJobNameEdit
        {
            get
            {
                if ((this.mUIJobNameEdit == null))
                {
                    this.mUIJobNameEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIJobNameEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "jobName";
                    this.mUIJobNameEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIJobNameEdit;
            }
        }
        
        public WpfComboBox UIJobProjComboBox
        {
            get
            {
                if ((this.mUIJobProjComboBox == null))
                {
                    this.mUIJobProjComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIJobProjComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "jobProj";
                    this.mUIJobProjComboBox.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIJobProjComboBox;
            }
        }
        
        public WpfDatePicker UIJobStartDatePicker
        {
            get
            {
                if ((this.mUIJobStartDatePicker == null))
                {
                    this.mUIJobStartDatePicker = new WpfDatePicker(this);
                    #region Search Criteria
                    this.mUIJobStartDatePicker.SearchProperties[WpfDatePicker.PropertyNames.AutomationId] = "jobStart";
                    this.mUIJobStartDatePicker.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIJobStartDatePicker;
            }
        }
        
        public WpfDatePicker UIJobEndDatePicker
        {
            get
            {
                if ((this.mUIJobEndDatePicker == null))
                {
                    this.mUIJobEndDatePicker = new WpfDatePicker(this);
                    #region Search Criteria
                    this.mUIJobEndDatePicker.SearchProperties[WpfDatePicker.PropertyNames.AutomationId] = "jobEnd";
                    this.mUIJobEndDatePicker.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIJobEndDatePicker;
            }
        }
        
        public WpfButton UISpeichernButton1
        {
            get
            {
                if ((this.mUISpeichernButton1 == null))
                {
                    this.mUISpeichernButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUISpeichernButton1.SearchProperties[WpfButton.PropertyNames.AutomationId] = "jobSubmit";
                    this.mUISpeichernButton1.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton1;
            }
        }
        
        public WpfComboBox UIJobMitComboBox
        {
            get
            {
                if ((this.mUIJobMitComboBox == null))
                {
                    this.mUIJobMitComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIJobMitComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "jobMit";
                    this.mUIJobMitComboBox.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIJobMitComboBox;
            }
        }
        
        public UIJobsListBoxList UIJobsListBoxList
        {
            get
            {
                if ((this.mUIJobsListBoxList == null))
                {
                    this.mUIJobsListBoxList = new UIJobsListBoxList(this);
                }
                return this.mUIJobsListBoxList;
            }
        }
        
        public UIItemList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new UIItemList(this);
                }
                return this.mUIItemList;
            }
        }
        
        public WpfText UIDoppeleinsatzfürMitaText
        {
            get
            {
                if ((this.mUIDoppeleinsatzfürMitaText == null))
                {
                    this.mUIDoppeleinsatzfürMitaText = new WpfText(this);
                    #region Search Criteria
                    this.mUIDoppeleinsatzfürMitaText.SearchProperties[WpfText.PropertyNames.AutomationId] = "success";
                    this.mUIDoppeleinsatzfürMitaText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIDoppeleinsatzfürMitaText;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIMitNameEdit;
        
        private WpfEdit mUIMitVornameEdit;
        
        private WpfCheckBox mUIMitAktivCheckBox;
        
        private WpfButton mUISpeichernButton;
        
        private UIMitListBoxList mUIMitListBoxList;
        
        private WpfEdit mUIJobNameEdit;
        
        private WpfComboBox mUIJobProjComboBox;
        
        private WpfDatePicker mUIJobStartDatePicker;
        
        private WpfDatePicker mUIJobEndDatePicker;
        
        private WpfButton mUISpeichernButton1;
        
        private WpfComboBox mUIJobMitComboBox;
        
        private UIJobsListBoxList mUIJobsListBoxList;
        
        private UIItemList mUIItemList;
        
        private WpfText mUIDoppeleinsatzfürMitaText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMitListBoxList : WpfList
    {
        
        public UIMitListBoxList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfList.PropertyNames.AutomationId] = "mitListBox";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfListItem UIJohnListItem
        {
            get
            {
                if ((this.mUIJohnListItem == null))
                {
                    this.mUIJohnListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUIJohnListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "John";
                    this.mUIJohnListItem.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIJohnListItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfListItem mUIJohnListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIJobsListBoxList : WpfList
    {
        
        public UIJobsListBoxList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfList.PropertyNames.AutomationId] = "jobsListBox";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfListItem UITestListItem
        {
            get
            {
                if ((this.mUITestListItem == null))
                {
                    this.mUITestListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUITestListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "Test";
                    this.mUITestListItem.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITestListItem;
            }
        }
        
        public WpfListItem UITest1682016120000AMListItem
        {
            get
            {
                if ((this.mUITest1682016120000AMListItem == null))
                {
                    this.mUITest1682016120000AMListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUITest1682016120000AMListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "Test1 - 6/8/2016 12:00:00 AM";
                    this.mUITest1682016120000AMListItem.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITest1682016120000AMListItem;
            }
        }
        
        public WpfListItem UITest662016120000AMListItem
        {
            get
            {
                if ((this.mUITest662016120000AMListItem == null))
                {
                    this.mUITest662016120000AMListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUITest662016120000AMListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "Test - 6/6/2016 12:00:00 AM";
                    this.mUITest662016120000AMListItem.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITest662016120000AMListItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfListItem mUITestListItem;
        
        private WpfListItem mUITest1682016120000AMListItem;
        
        private WpfListItem mUITest662016120000AMListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemList : WpfList
    {
        
        public UIItemList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfList.PropertyNames.Instance] = "7";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfListItem UITest1ListItem
        {
            get
            {
                if ((this.mUITest1ListItem == null))
                {
                    this.mUITest1ListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUITest1ListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "Test1";
                    this.mUITest1ListItem.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITest1ListItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfListItem mUITest1ListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainWindowWindow1 : WinWindow
    {
        
        public UIMainWindowWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
